name: Release NuGet Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: 恢复依赖
        run: nuget restore PlainNamedBinaryTag.sln

      - name: 构建项目
        run: msbuild PlainNamedBinaryTag/PlainNamedBinaryTag.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: 设置 nuspec 版本号
        run: |
          $version = "${{ github.event.release.tag_name }}"
          $version = $version.TrimStart("v")
          (Get-Content PlainNamedBinaryTag.nuspec) -replace '<version>.*</version>', "<version>$version</version>" | Set-Content PlainNamedBinaryTag.nuspec

      - name: 打包 NuGet
        run: nuget pack PlainNamedBinaryTag.nuspec

      - name: 发布到 NuGet
        run: nuget push PlainNamedBinaryTag.*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json

      - name: 上传到 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: PlainNamedBinaryTag.*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}